insert into universities (name, short_name, city, country) values
  ('Abubakar Tafawa Balewa University', 'ATBU', 'Bauchi', 'Nigeria'),
  ('Adeyemi Federal University of Education', null, 'Ondo', 'Nigeria'),
  ('Air Force Institute of Technology', 'AFIT', 'Kaduna', 'Nigeria'),
  ('Alex Ekwueme Federal University Ndufu-Alike', 'AE-FUNAI', 'Ikwo', 'Nigeria'),
  ('Alvan Ikoku Federal University of Education', null, 'Owerri', 'Nigeria'),
  ('Bayero University', 'BUK', 'Kano', 'Nigeria'),
  ('Federal University Birnin Kebbi', null, 'Birnin Kebbi', 'Nigeria'),
  ('Federal University Dutse', null, 'Dutse', 'Nigeria'),
  ('Federal University Dutsin-Ma', null, 'Dutsin-Ma', 'Nigeria'),
  ('Federal University Gashua', null, 'Gashua', 'Nigeria'),
  ('Federal University Gusau', null, 'Gusau', 'Nigeria'),
  ('Federal University Kashere', null, 'Kashere', 'Nigeria'),
  ('Federal University Lafia', null, 'Lafia', 'Nigeria'),
  ('Federal University Lokoja', null, 'Lokoja', 'Nigeria'),
  ('Federal University of Agriculture, Abeokuta', 'FUNAAB', 'Abeokuta', 'Nigeria'),
  ('Federal University of Agriculture, Zuru', null, 'Zuru', 'Nigeria'),
  ('Federal University of Applied Sciences, Kachia', null, 'Kachia', 'Nigeria'),
  ('Federal University of Education, Pankshin', null, 'Pankshin', 'Nigeria'),
  ('Federal University of Education, Zaria', null, 'Zaria', 'Nigeria'),
  ('Federal University of Health Sciences, Azare', null, 'Azare', 'Nigeria'),
  ('Federal University of Petroleum Resources, Effurun', 'FUPRE', 'Effurun', 'Nigeria'),
  ('Federal University of Technology, Akure', 'FUTA', 'Akure', 'Nigeria'),
  ('Federal University of Technology, Minna', 'FUTMINNA', 'Minna', 'Nigeria'),
  ('Federal University of Technology, Owerri', 'FUTO', 'Owerri', 'Nigeria'),
  ('Federal University of Transportation, Daura', null, 'Daura', 'Nigeria'),
  ('Federal University Otuoke', null, 'Otuoke', 'Nigeria'),
  ('Federal University Oye-Ekiti', 'FUOYE', 'Oye-Ekiti', 'Nigeria'),
  ('Federal University Wukari', null, 'Wukari', 'Nigeria'),
  ('Joseph Sarwuan Tarka University', 'JOSTUM', 'Makurdi', 'Nigeria'),
  ('Michael Okpara University of Agriculture', 'MOUAU', 'Umudike', 'Nigeria'),
  ('Modibbo Adama University of Technology', 'MAUTECH', 'Yola', 'Nigeria'),
  ('National Open University of Nigeria', 'NOUN', 'Victoria Island', 'Nigeria'),
  ('Nigerian Army University, Biu', null, 'Biu', 'Nigeria'),
  ('Nigerian Defence Academy', 'NDA', 'Kaduna', 'Nigeria'),
  ('Nigerian Maritime University', null, 'Okerenkoko', 'Nigeria'),
  ('Nnamdi Azikiwe University', 'UNIZIK', 'Awka', 'Nigeria'),
  ('Obafemi Awolowo University', 'OAU', 'Ile-Ife', 'Nigeria'),
  ('Tai Solarin Federal University of Education', null, 'Ijebu-Ode', 'Nigeria'),
  ('University of Benin', 'UNIBEN', 'Benin City', 'Nigeria'),
  ('University of Calabar', 'UNICAL', 'Calabar', 'Nigeria'),
  ('University of Ilorin', 'UNILORIN', 'Ilorin', 'Nigeria'),
  ('University of Jos', 'UNIJOS', 'Jos', 'Nigeria'),
  ('University of Maiduguri', 'UNIMAID', 'Maiduguri', 'Nigeria'),
  ('University of Port Harcourt', 'UNIPORT', 'Port Harcourt', 'Nigeria'),
  ('University of Uyo', 'UNIUYO', 'Uyo', 'Nigeria');